# Generated by Django 4.1.3 on 2022-12-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="color",
            field=models.CharField(
                default="white", max_length=50, verbose_name="Цвет"
            ),
        ),
    ]
