# Generated by Django 4.1.3 on 2022-12-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        help_text="Указывайте без знака вопрос",
                        max_length=200,
                        null=True,
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "op1",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Вариант 1"
                    ),
                ),
                (
                    "op2",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Вариант 2"
                    ),
                ),
                (
                    "op3",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Вариант 3"
                    ),
                ),
                (
                    "op4",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Вариант 4"
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        help_text="Выберите номер варианта",
                        max_length=200,
                        null=True,
                        verbose_name="Ответ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
                "ordering": ("-pk",),
            },
        ),
        migrations.CreateModel(
            name="PassedQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пройденный тест пользователя",
                "verbose_name_plural": "Пройденные тесты пользователя",
                "ordering": ("-pk",),
            },
        ),
    ]
