# Generated by Django 4.1.3 on 2022-12-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuizModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Вопрос"
                    ),
                ),
                (
                    "op1",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Вариант 1"
                    ),
                ),
                (
                    "op2",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Вариант 2"
                    ),
                ),
                (
                    "op3",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Вариант 3"
                    ),
                ),
                (
                    "op4",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Вариант 4"
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Ответ"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
                "ordering": ("-pk",),
            },
        ),
    ]
